### Create Email
POST http://localhost:3000/api/processEmails
Content-Type: application/json

{
  "inboxToProcess": "movemenTech-RBG@movementor.online",
  "toRecipients": ["Kundendialog@rheinbahn.de"],
  "ccRecipients": ["Brit.Wildau@rheinbahn.de", "daniel@movementor.online", "norman@movementor.online"],
  "nonCategoryRecipients": ["Kundendialog@rheinbahn.de", "Brit.Wildau@rheinbahn.de","daniel@movementor.online", "norman@movementor.online"]
}